ADJ_PREPS = [
    {"adjective": "afraid",       "preposition": "of",    "translation": "бояться чего-л.",
     "example": "She is afraid of spiders.",              "options": ["of",   "about", "from"]},
    {"adjective": "nervous",      "preposition": "about", "translation": "нервничать из-за чего-л.",
     "example": "He is nervous about the exam.",          "options": ["about","of",    "for"]},
    {"adjective": "interested",   "preposition": "in",    "translation": "интересоваться чем-л.",
     "example": "She is interested in art.",              "options": ["in",   "about", "of"]},
    {"adjective": "tired",        "preposition": "of",    "translation": "устать от чего-л.",
     "example": "I am tired of waiting.",                 "options": ["of",   "from",  "with"]},
    {"adjective": "proud",        "preposition": "of",    "translation": "гордиться чем-л.",
     "example": "They are proud of their son.",           "options": ["of",   "about", "for"]},
    {"adjective": "worried",      "preposition": "about", "translation": "беспокоиться о чём-л.",
     "example": "She is worried about her health.",       "options": ["about","of",    "for"]},
    {"adjective": "sorry",        "preposition": "for",   "translation": "сожалеть / извиняться",
     "example": "I am sorry for the mistake.",            "options": ["for",  "about", "of"]},
    {"adjective": "responsible",  "preposition": "for",   "translation": "отвечать за что-л.",
     "example": "She is responsible for the project.",    "options": ["for",  "of",    "about"]},
    {"adjective": "famous",       "preposition": "for",   "translation": "известен чем-л.",
     "example": "Paris is famous for the Eiffel Tower.",  "options": ["for",  "of",    "about"]},
    {"adjective": "excited",      "preposition": "about", "translation": "в предвкушении / взволнован",
     "example": "She is excited about the trip.",         "options": ["about","for",   "of"]},
    {"adjective": "surprised",    "preposition": "by",    "translation": "удивлён чем-л.",
     "example": "I was surprised by the news.",           "options": ["by",   "about", "at"]},
    {"adjective": "angry",        "preposition": "with",  "translation": "злиться на кого-л.",
     "example": "She is angry with her brother.",         "options": ["with", "at",    "about"]},
    {"adjective": "bored",        "preposition": "with",  "translation": "скучать / надоело",
     "example": "He is bored with his job.",              "options": ["with", "of",    "about"]},
    {"adjective": "satisfied",    "preposition": "with",  "translation": "доволен чем-л.",
     "example": "Are you satisfied with the result?",     "options": ["with", "about", "of"]},
    {"adjective": "different",    "preposition": "from",  "translation": "отличаться от чего-л.",
     "example": "This is different from what I expected.","options": ["from", "than",  "to"]},
    {"adjective": "aware",        "preposition": "of",    "translation": "осознавать / знать о чём-л.",
     "example": "Are you aware of the risks?",            "options": ["of",   "about", "in"]},
    {"adjective": "fond",         "preposition": "of",    "translation": "любить / быть привязанным",
     "example": "She is fond of classical music.",        "options": ["of",   "about", "with"]},
    {"adjective": "capable",      "preposition": "of",    "translation": "способен на что-л.",
     "example": "He is capable of great things.",         "options": ["of",   "for",   "to"]},
    {"adjective": "happy",        "preposition": "with",  "translation": "рад / доволен чем-л.",
     "example": "I am happy with my decision.",           "options": ["with", "about", "of"]},
    {"adjective": "disappointed", "preposition": "with",  "translation": "разочарован чем-л.",
     "example": "She was disappointed with the film.",    "options": ["with", "in",    "about"]},
    {"adjective": "similar",      "preposition": "to",    "translation": "похож на что-л.",
     "example": "This painting is similar to that one.",  "options": ["to",   "from",  "with"]},
    {"adjective": "ready",        "preposition": "for",   "translation": "готов к чему-л.",
     "example": "Are you ready for the test?",            "options": ["for",  "to",    "about"]},
    {"adjective": "grateful",     "preposition": "for",   "translation": "благодарен за что-л.",
     "example": "I am grateful for your help.",           "options": ["for",  "to",    "about"]},
    {"adjective": "keen",         "preposition": "on",    "translation": "увлечён чем-л.",
     "example": "She is keen on photography.",            "options": ["on",   "about", "in"]},
]
