ADJ_PREPS = [

    # ─── of ──────────────────────────────────────────────────────────────────

    {"adjective": "afraid",       "preposition": "of",
     "translation": "бояться чего-л.",
     "example": "She is afraid of spiders.",
     "rule": "afraid / scared / terrified of — страх перед чем-л. конкретным",
     "options": ["of", "about", "from"]},
    {"adjective": "scared",       "preposition": "of",
     "translation": "бояться, испугаться",
     "example": "The child was scared of the dark.",
     "rule": "scared of — разговорный синоним afraid of",
     "options": ["of", "about", "from"]},
    {"adjective": "proud",        "preposition": "of",
     "translation": "гордиться чем-л.",
     "example": "They are proud of their son.",
     "rule": "proud of — гордость за достижение или человека",
     "options": ["of", "about", "for"]},
    {"adjective": "tired",        "preposition": "of",
     "translation": "устать от чего-л., надоело",
     "example": "I am tired of waiting.",
     "rule": "tired of — раздражение или усталость от повторяющегося действия",
     "options": ["of", "from", "with"]},
    {"adjective": "aware",        "preposition": "of",
     "translation": "осознавать, знать о чём-л.",
     "example": "Are you aware of the risks?",
     "rule": "aware of — знание о факте или ситуации",
     "options": ["of", "about", "in"]},
    {"adjective": "fond",         "preposition": "of",
     "translation": "любить, быть привязанным к чему-л.",
     "example": "She is very fond of classical music.",
     "rule": "fond of — тёплая привязанность к чему-л. или кому-л.",
     "options": ["of", "about", "with"]},
    {"adjective": "capable",      "preposition": "of",
     "translation": "способен на что-л.",
     "example": "He is capable of great things.",
     "rule": "capable of — наличие способности или потенциала",
     "options": ["of", "for", "to"]},
    {"adjective": "ashamed",      "preposition": "of",
     "translation": "стыдиться чего-л.",
     "example": "She was ashamed of her behaviour.",
     "rule": "ashamed of — стыд за собственный поступок или черту",
     "options": ["of", "about", "for"]},
    {"adjective": "jealous",      "preposition": "of",
     "translation": "ревновать / завидовать кому-л.",
     "example": "He was jealous of his colleague's success.",
     "rule": "jealous of — ревность или зависть по отношению к кому-л.",
     "options": ["of", "about", "with"]},
    {"adjective": "full",         "preposition": "of",
     "translation": "полный чего-л.",
     "example": "The room was full of people.",
     "rule": "full of — содержание или насыщенность чем-л.",
     "options": ["of", "with", "in"]},
    {"adjective": "guilty",       "preposition": "of",
     "translation": "виновен в чём-л.",
     "example": "He was found guilty of fraud.",
     "rule": "guilty of — юридическая или моральная вина за конкретное действие",
     "options": ["of", "for", "about"]},
    {"adjective": "suspicious",   "preposition": "of",
     "translation": "подозревать кого-л./что-л.",
     "example": "She was suspicious of his motives.",
     "rule": "suspicious of — недоверие, подозрение в отношении кого-л.",
     "options": ["of", "about", "with"]},
    {"adjective": "typical",      "preposition": "of",
     "translation": "типично для кого-л./чего-л.",
     "example": "That kind of mistake is typical of beginners.",
     "rule": "typical of — характерная черта, свойственная кому-л. или чему-л.",
     "options": ["of", "for", "to"]},
    {"adjective": "short",        "preposition": "of",
     "translation": "нехватать, испытывать дефицит",
     "example": "We are short of time.",
     "rule": "short of — недостаток чего-л. (времени, денег, ресурсов)",
     "options": ["of", "on", "in"]},

    # ─── about ────────────────────────────────────────────────────────────────

    {"adjective": "nervous",      "preposition": "about",
     "translation": "нервничать из-за чего-л.",
     "example": "He is nervous about the exam.",
     "rule": "nervous / worried / excited about — эмоция по поводу конкретной ситуации",
     "options": ["about", "of", "for"]},
    {"adjective": "worried",      "preposition": "about",
     "translation": "беспокоиться о чём-л.",
     "example": "She is worried about her health.",
     "rule": "worried about — тревога по поводу возможной проблемы",
     "options": ["about", "of", "for"]},
    {"adjective": "excited",      "preposition": "about",
     "translation": "в предвкушении, взволнован",
     "example": "She is excited about the trip.",
     "rule": "excited about — позитивное волнение в ожидании события",
     "options": ["about", "for", "of"]},
    {"adjective": "upset",        "preposition": "about",
     "translation": "расстроен из-за чего-л.",
     "example": "He was upset about losing the game.",
     "rule": "upset about — огорчение из-за конкретного события",
     "options": ["about", "of", "with"]},
    {"adjective": "enthusiastic", "preposition": "about",
     "translation": "полон энтузиазма, воодушевлён",
     "example": "She is enthusiastic about the new project.",
     "rule": "enthusiastic about — сильный интерес или воодушевление",
     "options": ["about", "for", "in"]},
    {"adjective": "passionate",   "preposition": "about",
     "translation": "страстно увлечён чем-л.",
     "example": "He is passionate about music.",
     "rule": "passionate about — глубокое увлечение, призвание",
     "options": ["about", "for", "in"]},
    {"adjective": "confident",    "preposition": "about",
     "translation": "уверен в чём-л.",
     "example": "She felt confident about the presentation.",
     "rule": "confident about (ситуация) / confident in (человек или способность)",
     "options": ["about", "in", "of"]},

    # ─── for ──────────────────────────────────────────────────────────────────

    {"adjective": "sorry",        "preposition": "for",
     "translation": "сожалеть / извиняться за что-л.",
     "example": "I am sorry for the mistake.",
     "rule": "sorry for — сожаление о собственном поступке",
     "options": ["for", "about", "of"]},
    {"adjective": "responsible",  "preposition": "for",
     "translation": "нести ответственность за что-л.",
     "example": "She is responsible for the whole project.",
     "rule": "responsible for — ответственность за конкретную область или действие",
     "options": ["for", "of", "about"]},
    {"adjective": "famous",       "preposition": "for",
     "translation": "известен чем-л.",
     "example": "Paris is famous for the Eiffel Tower.",
     "rule": "famous / known / celebrated for — известность благодаря конкретному качеству",
     "options": ["for", "of", "about"]},
    {"adjective": "ready",        "preposition": "for",
     "translation": "готов к чему-л.",
     "example": "Are you ready for the test?",
     "rule": "ready for — готовность к предстоящему событию или задаче",
     "options": ["for", "to", "about"]},
    {"adjective": "grateful",     "preposition": "for",
     "translation": "благодарен за что-л.",
     "example": "I am grateful for your help.",
     "rule": "grateful / thankful for — благодарность за конкретное действие или вещь",
     "options": ["for", "to", "about"]},
    {"adjective": "eligible",     "preposition": "for",
     "translation": "иметь право на что-л.",
     "example": "Are you eligible for a discount?",
     "rule": "eligible for — соответствие требованиям для получения чего-л.",
     "options": ["for", "to", "of"]},

    # ─── with ─────────────────────────────────────────────────────────────────

    {"adjective": "angry",        "preposition": "with",
     "translation": "злиться на кого-л.",
     "example": "She is angry with her brother.",
     "rule": "angry with (человек) / angry about (ситуация) — источник злости меняет предлог",
     "options": ["with", "at", "about"]},
    {"adjective": "bored",        "preposition": "with",
     "translation": "скучать, надоело",
     "example": "He is bored with his job.",
     "rule": "bored with — скука от чего-л. привычного или монотонного",
     "options": ["with", "of", "about"]},
    {"adjective": "satisfied",    "preposition": "with",
     "translation": "доволен чем-л.",
     "example": "Are you satisfied with the result?",
     "rule": "satisfied / pleased / happy with — удовлетворённость результатом",
     "options": ["with", "about", "of"]},
    {"adjective": "happy",        "preposition": "with",
     "translation": "рад, доволен чем-л.",
     "example": "I am happy with my decision.",
     "rule": "happy with — довольствие конкретной ситуацией или результатом",
     "options": ["with", "about", "of"]},
    {"adjective": "disappointed", "preposition": "with",
     "translation": "разочарован чем-л.",
     "example": "She was disappointed with the film.",
     "rule": "disappointed with (результат/вещь) / disappointed in (человек)",
     "options": ["with", "in", "about"]},
    {"adjective": "impressed",    "preposition": "with",
     "translation": "впечатлён чем-л.",
     "example": "Everyone was impressed with her performance.",
     "rule": "impressed with / by — оба варианта верны; with — чуть разговорнее",
     "options": ["with", "by", "about"]},
    {"adjective": "obsessed",     "preposition": "with",
     "translation": "одержимый, зациклен на чём-л.",
     "example": "He is obsessed with video games.",
     "rule": "obsessed with — навязчивый интерес или зацикленность на чём-л.",
     "options": ["with", "about", "by"]},
    {"adjective": "familiar",     "preposition": "with",
     "translation": "знакомый с чем-л., хорошо знать",
     "example": "Are you familiar with this software?",
     "rule": "familiar with — наличие знаний или опыта в области",
     "options": ["with", "about", "of"]},
    {"adjective": "fed up",       "preposition": "with",
     "translation": "сыт по горло, устал от чего-л.",
     "example": "I'm fed up with all these delays.",
     "rule": "fed up with — сильное раздражение от повторяющейся проблемы",
     "options": ["with", "of", "about"]},
    {"adjective": "patient",      "preposition": "with",
     "translation": "терпеливый по отношению к кому-л.",
     "example": "Try to be patient with the children.",
     "rule": "patient with (человек) — терпение в отношении чьего-л. поведения",
     "options": ["with", "about", "for"]},

    # ─── in ───────────────────────────────────────────────────────────────────

    {"adjective": "interested",   "preposition": "in",
     "translation": "интересоваться чем-л.",
     "example": "She is very interested in art.",
     "rule": "interested in — наличие интереса к теме или деятельности",
     "options": ["in", "about", "of"]},
    {"adjective": "involved",     "preposition": "in",
     "translation": "участвовать в чём-л., быть причастным",
     "example": "She was involved in the decision.",
     "rule": "involved in — участие в процессе или деятельности",
     "options": ["in", "with", "at"]},
    {"adjective": "experienced",  "preposition": "in",
     "translation": "опытный в чём-л.",
     "example": "He is very experienced in project management.",
     "rule": "experienced in — наличие практического опыта в области",
     "options": ["in", "at", "with"]},
    {"adjective": "successful",   "preposition": "in",
     "translation": "преуспеть в чём-л.",
     "example": "She was successful in her career.",
     "rule": "successful in — достижение успеха в конкретной сфере",
     "options": ["in", "at", "with"]},

    # ─── at ───────────────────────────────────────────────────────────────────

    {"adjective": "good",         "preposition": "at",
     "translation": "хорошо уметь что-л.",
     "example": "She is very good at maths.",
     "rule": "good / bad / brilliant / terrible at — уровень умения или навыка",
     "options": ["at", "in", "with"]},
    {"adjective": "bad",          "preposition": "at",
     "translation": "плохо уметь что-л.",
     "example": "He admits he is bad at remembering names.",
     "rule": "bad at — слабая сторона, область где не хватает умения",
     "options": ["at", "in", "with"]},
    {"adjective": "brilliant",    "preposition": "at",
     "translation": "блестяще владеть чем-л.",
     "example": "She is brilliant at solving complex problems.",
     "rule": "brilliant / excellent / hopeless at — уровень мастерства",
     "options": ["at", "in", "for"]},
    {"adjective": "surprised",    "preposition": "at",
     "translation": "удивлён чем-л.",
     "example": "I was surprised at how quickly she learned.",
     "rule": "surprised at (результат/факт) / surprised by (действие) — оба варианта возможны",
     "options": ["at", "by", "about"]},
    {"adjective": "shocked",      "preposition": "at",
     "translation": "потрясён, шокирован чем-л.",
     "example": "Everyone was shocked at the news.",
     "rule": "shocked at / by — сильное потрясение от неожиданного события",
     "options": ["at", "by", "about"]},

    # ─── to ───────────────────────────────────────────────────────────────────

    {"adjective": "similar",      "preposition": "to",
     "translation": "похож на что-л.",
     "example": "This painting is similar to that one.",
     "rule": "similar to — сходство между двумя объектами (ср.: different from)",
     "options": ["to", "from", "with"]},
    {"adjective": "used",         "preposition": "to",
     "translation": "привыкший к чему-л. (be used to)",
     "example": "She is used to working late.",
     "rule": "be used to + -ing/-noun: привычка; ≠ used to + bare inf. (прошлая привычка)",
     "options": ["to", "with", "for"]},
    {"adjective": "devoted",      "preposition": "to",
     "translation": "преданный чему-л., посвятить себя",
     "example": "She is devoted to her work.",
     "rule": "devoted / dedicated / committed to — глубокая преданность делу или человеку",
     "options": ["to", "for", "of"]},
    {"adjective": "married",      "preposition": "to",
     "translation": "женат / замужем за кем-л.",
     "example": "She has been married to him for ten years.",
     "rule": "married to (человек) — не married with!",
     "options": ["to", "with", "for"]},
    {"adjective": "opposed",      "preposition": "to",
     "translation": "выступать против чего-л.",
     "example": "They are opposed to any changes.",
     "rule": "opposed to — несогласие или противостояние",
     "options": ["to", "against", "about"]},
    {"adjective": "related",      "preposition": "to",
     "translation": "связан с чем-л. / родственник",
     "example": "Is this problem related to the previous one?",
     "rule": "related to — связь между понятиями или людьми",
     "options": ["to", "with", "of"]},
    {"adjective": "allergic",     "preposition": "to",
     "translation": "страдать аллергией на что-л.",
     "example": "He is allergic to peanuts.",
     "rule": "allergic to — медицинская аллергическая реакция",
     "options": ["to", "of", "from"]},

    # ─── on ───────────────────────────────────────────────────────────────────

    {"adjective": "keen",         "preposition": "on",
     "translation": "увлечён чем-л.",
     "example": "She is keen on photography.",
     "rule": "keen on — энтузиазм и живой интерес к занятию",
     "options": ["on", "about", "in"]},
    {"adjective": "dependent",    "preposition": "on",
     "translation": "зависеть от чего-л./кого-л.",
     "example": "Children are dependent on their parents.",
     "rule": "dependent on — зависимость, невозможность обойтись без чего-л.",
     "options": ["on", "of", "from"]},
    {"adjective": "focused",      "preposition": "on",
     "translation": "сосредоточен на чём-л.",
     "example": "Stay focused on your goal.",
     "rule": "focused on — концентрация внимания на конкретной задаче или цели",
     "options": ["on", "at", "in"]},
    {"adjective": "based",        "preposition": "on",
     "translation": "основан на чём-л.",
     "example": "The film is based on a true story.",
     "rule": "based on — источник или основание чего-л.",
     "options": ["on", "in", "from"]},

    # ─── by ───────────────────────────────────────────────────────────────────

    {"adjective": "impressed",    "preposition": "by",
     "translation": "впечатлён чем-л.",
     "example": "I was impressed by her dedication.",
     "rule": "impressed by / with — оба верны; by — чуть более формально",
     "options": ["by", "with", "about"]},

    # ─── from ─────────────────────────────────────────────────────────────────

    {"adjective": "different",    "preposition": "from",
     "translation": "отличаться от чего-л.",
     "example": "This is completely different from what I expected.",
     "rule": "different from (BrE/AmE) — сравнение; не «different than» в официальном стиле",
     "options": ["from", "than", "to"]},
]
