"""Card difficulty tiers (1=Базовый, 2=Средний, 3=Продвинутый).
Verbs follow CEFR frequency (top ~40 = tier 1); other types are tiered
by how common/tricky the rule is. Generated, but safe to hand-edit.
"""

LEVELS = {
    "verbs": {
        'be': 1,
        'beat': 3,
        'become': 1,
        'begin': 1,
        'bend': 3,
        'bite': 3,
        'blow': 3,
        'break': 2,
        'bring': 1,
        'build': 2,
        'burn': 3,
        'buy': 1,
        'catch': 2,
        'choose': 2,
        'come': 1,
        'cost': 2,
        'cut': 2,
        'deal': 3,
        'dig': 3,
        'do': 1,
        'draw': 2,
        'drink': 1,
        'drive': 1,
        'eat': 1,
        'fall': 1,
        'feed': 3,
        'feel': 1,
        'fight': 2,
        'find': 1,
        'fly': 1,
        'forget': 2,
        'freeze': 3,
        'get': 1,
        'give': 1,
        'go': 1,
        'grow': 1,
        'hang': 3,
        'have': 1,
        'hear': 1,
        'hide': 2,
        'hit': 2,
        'hold': 1,
        'hurt': 3,
        'keep': 1,
        'know': 1,
        'lay': 3,
        'lead': 1,
        'leave': 1,
        'lend': 3,
        'let': 1,
        'light': 3,
        'lose': 1,
        'make': 1,
        'mean': 1,
        'meet': 1,
        'pay': 1,
        'put': 1,
        'quit': 3,
        'read': 1,
        'ride': 2,
        'rise': 3,
        'run': 1,
        'say': 1,
        'see': 1,
        'sell': 1,
        'send': 1,
        'shake': 3,
        'shoot': 3,
        'show': 1,
        'shut': 3,
        'sing': 2,
        'sink': 3,
        'sit': 1,
        'sleep': 1,
        'slide': 3,
        'speak': 1,
        'spend': 1,
        'spread': 3,
        'stand': 1,
        'steal': 3,
        'stick': 3,
        'strike': 3,
        'sweep': 3,
        'swim': 2,
        'take': 1,
        'teach': 2,
        'tear': 3,
        'tell': 1,
        'think': 1,
        'throw': 2,
        'understand': 1,
        'upset': 3,
        'wake': 2,
        'wear': 2,
        'win': 1,
        'wind': 3,
        'write': 1,
        'bear': 3,
        'bet': 2,
        'burst': 3,
        'dream': 2,
        'forbid': 3,
        'forgive': 2,
        'learn': 1,
        'lie': 2,
        'prove': 3,
        'ring': 1,
        'seek': 3,
        'set': 1,
        'shine': 2,
        'smell': 3,
        'spell': 3,
        'spill': 3,
        'split': 2,
        'spoil': 3,
        'swear': 2,
        'swing': 3,
    },
    "vp": {
        'enjoy': 2,
        'dislike': 3,
        'mind': 2,
        'fancy': 2,
        'miss': 2,
        'finish': 1,
        'avoid': 2,
        'delay': 3,
        'postpone': 3,
        'resist': 3,
        'deny': 2,
        'admit': 2,
        'keep': 2,
        'practise': 2,
        'risk': 3,
        'involve': 3,
        'consider': 2,
        'imagine': 2,
        'recall': 3,
        'suggest': 2,
        'recommend': 2,
        'want': 1,
        'give up': 1,
        'put off': 2,
        'carry on': 2,
        'look forward to': 1,
        'feel like': 2,
        "can't stand": 2,
        "can't help": 3,
        'threaten': 3,
        'hesitate': 2,
        'struggle': 3,
        'deserve': 2,
        'happen': 3,
        'hope': 1,
        'plan': 1,
        'intend': 3,
        'decide': 1,
        'choose': 2,
        'agree': 1,
        'refuse': 2,
        'offer': 2,
        'promise': 1,
        'demand': 3,
        'manage': 2,
        'fail': 2,
        'afford': 2,
        'seem': 2,
        'appear': 3,
        'tend': 2,
        'pretend': 2,
        'expect': 2,
        'prepare': 2,
        'learn': 1,
        'arrange': 2,
        'stop  (прекратить)': 2,
        'stop  (остановиться чтобы)': 2,
        'remember  (о прошлом)': 2,
        'remember  (о будущем)': 1,
        'try  (эксперимент)': 3,
        'try  (попытка)': 2,
        'forget  (о прошлом)': 2,
        'forget  (о будущем)': 1,
    },
    "adjprep": {
        'afraid': 1,
        'scared': 1,
        'proud': 1,
        'tired': 1,
        'aware': 2,
        'fond': 2,
        'capable': 2,
        'ashamed': 2,
        'jealous': 2,
        'full': 2,
        'guilty': 3,
        'suspicious': 3,
        'typical': 3,
        'short': 3,
        'nervous': 1,
        'worried': 1,
        'addicted': 2,
        'amazed': 2,
        'anxious': 2,
        'attached': 2,
        'curious': 1,
        'envious': 3,
        'hopeless': 3,
        'identical': 3,
        'polite': 1,
        'popular': 1,
        'rude': 1,
        'terrified': 2,
        'excited': 1,
        'upset': 2,
        'enthusiastic': 3,
        'passionate': 3,
        'confident': 2,
        'sorry': 1,
        'responsible': 2,
        'famous': 1,
        'ready': 1,
        'grateful': 2,
        'eligible': 3,
        'angry': 1,
        'bored': 2,
        'satisfied': 2,
        'happy': 1,
        'disappointed': 2,
        'obsessed': 3,
        'familiar': 2,
        'fed up': 3,
        'patient': 2,
        'interested': 1,
        'involved': 2,
        'experienced': 2,
        'successful': 2,
        'good': 1,
        'bad': 1,
        'brilliant': 2,
        'surprised': 2,
        'shocked': 2,
        'similar': 1,
        'used': 2,
        'devoted': 3,
        'married': 1,
        'opposed': 3,
        'related': 2,
        'allergic': 3,
        'keen': 2,
        'dependent': 3,
        'focused': 2,
        'based': 2,
        'impressed': 2,
        'different': 1,
    },
    "prep": {
        'She works {?} a hospital.': 1,
        'I live {?} Moscow.': 1,
        'He was born {?} 1995.': 1,
        'It always snows {?} winter.': 1,
        'The keys are {?} my pocket.': 1,
        'We met {?} the morning.': 1,
        "I'll be back {?} ten minutes.": 2,
        'I read about it {?} a newspaper.': 2,
        'She lives {?} the north of England.': 2,
        'He is {?} hospital recovering from the surgery.': 3,
        'She learned English {?} six months.': 3,
        'He is {?} a meeting right now.': 2,
        "There's a mistake {?} your essay.": 2,
        'He stood {?} the queue for an hour.': 3,
        'The meeting is {?} Monday.': 1,
        'My birthday is {?} the 15th of June.': 1,
        'The book is {?} the table.': 1,
        'She lives {?} Baker Street.': 1,
        'There is a picture {?} the wall.': 1,
        'I saw it {?} TV.': 2,
        'We went there {?} foot.': 2,
        'She is {?} the phone right now.': 2,
        'I read it {?} Facebook.': 2,
        'She is {?} holiday this week.': 2,
        'The flight arrived {?} time.': 3,
        'They live {?} the third floor.': 2,
        'She congratulated him {?} his promotion.': 3,
        'The conference is {?} the 5th of March.': 1,
        "The train leaves {?} 9 o'clock.": 1,
        'She is studying {?} university.': 1,
        "I'll meet you {?} the airport.": 1,
        'She is good {?} maths.': 2,
        'He arrived {?} the station.': 2,
        'They met {?} a party.': 1,
        'Look {?} that beautiful sunset!': 2,
        'She is working hard {?} the moment.': 3,
        'He is {?} home all day.': 1,
        'She is {?} work right now.': 1,
        'We arrived {?} midnight.': 2,
        'He knocked {?} the door.': 3,
        'She smiled {?} me from across the room.': 3,
        "Let's meet {?} the entrance.": 2,
        'The children are {?} school today.': 1,
        'We arrived just {?} time for the last train.': 3,
        'Who is the woman {?} this photo?': 2,
        "There's a big table {?} the middle of the room.": 2,
        "He's still {?} bed — wake him up!": 1,
        'I paid {?} cash.': 2,
        "Sorry, I can't talk — I'm {?} a hurry.": 3,
        'They are {?} love and very happy.': 3,
        'There were no free seats {?} the bus.': 1,
        'I found this article {?} the internet.': 1,
        'The bathroom is the first door {?} the left.': 1,
        'We visit my grandparents {?} Christmas Day.': 2,
        'He is in London {?} business.': 3,
        "He didn't break it {?} purpose.": 3,
        'The exercises are {?} page 12.': 2,
        "I couldn't sleep {?} night.": 1,
        'Wait for me {?} the bus stop.': 1,
        '{?} the end of the film, everyone was crying.': 2,
        'It was love {?} first sight.': 3,
        "She's {?} lunch — call back in an hour.": 2,
        'Sign your name {?} the bottom of the page.': 2,
    },
}
