PREPOSITIONS = [

    # ─── IN ──────────────────────────────────────────────────────────────────
    # Принцип: внутри ограниченного пространства; периоды времени (не точки)

    {"sentence": "She works {?} a hospital.",
     "answer": "in",  "translation": "Она работает в больнице.",
     "rule": "in — внутри здания или учреждения (находишься внутри)"},
    {"sentence": "I live {?} Moscow.",
     "answer": "in",  "translation": "Я живу в Москве.",
     "rule": "in — города, страны, регионы (большие географические единицы)"},
    {"sentence": "He was born {?} 1995.",
     "answer": "in",  "translation": "Он родился в 1995 году.",
     "rule": "in — годы, десятилетия и века: in 1995 / in the 1990s / in the 20th century"},
    {"sentence": "It always snows {?} winter.",
     "answer": "in",  "translation": "Зимой всегда идёт снег.",
     "rule": "in — времена года: in spring / in summer / in autumn / in winter"},
    {"sentence": "The keys are {?} my pocket.",
     "answer": "in",  "translation": "Ключи у меня в кармане.",
     "rule": "in — внутри закрытого или ограниченного пространства"},
    {"sentence": "We met {?} the morning.",
     "answer": "in",  "translation": "Мы встретились утром.",
     "rule": "in — части суток: in the morning / afternoon / evening (но: at night!)"},
    {"sentence": "I'll be back {?} ten minutes.",
     "answer": "in",  "translation": "Я вернусь через десять минут.",
     "rule": "in + промежуток = через (говорим о будущем): in an hour, in two days"},
    {"sentence": "I read about it {?} a newspaper.",
     "answer": "in",  "translation": "Я прочитал об этом в газете.",
     "rule": "in — в печатных изданиях: in a book / magazine / newspaper"},
    {"sentence": "She lives {?} the north of England.",
     "answer": "in",  "translation": "Она живёт на севере Англии.",
     "rule": "in — части страны или региона: in the north / south / east / west"},
    {"sentence": "He is {?} hospital recovering from the surgery.",
     "answer": "in",  "translation": "Он в больнице, восстанавливается после операции.",
     "rule": "in hospital (BrE, без артикля) — находиться на лечении; ср. at the hospital = у здания"},
    {"sentence": "She learned English {?} six months.",
     "answer": "in",  "translation": "Она выучила английский за шесть месяцев.",
     "rule": "in + период = за (сколько времени заняло): I did it in a week"},
    {"sentence": "He is {?} a meeting right now.",
     "answer": "in",  "translation": "Он сейчас на совещании.",
     "rule": "in a meeting / in a class / in a lesson — занят внутри события"},
    {"sentence": "There's a mistake {?} your essay.",
     "answer": "in",  "translation": "В твоём эссе есть ошибка.",
     "rule": "in — в письменном тексте или документе"},
    {"sentence": "He stood {?} the queue for an hour.",
     "answer": "in",  "translation": "Он стоял в очереди целый час.",
     "rule": "in a queue / in a line — стоять в очереди"},

    # ─── ON ──────────────────────────────────────────────────────────────────
    # Принцип: на поверхности; дни и даты; средства связи и транспорт

    {"sentence": "The meeting is {?} Monday.",
     "answer": "on",  "translation": "Встреча в понедельник.",
     "rule": "on — дни недели: on Monday / on Friday / on weekdays"},
    {"sentence": "My birthday is {?} the 15th of June.",
     "answer": "on",  "translation": "Мой день рождения 15 июня.",
     "rule": "on — конкретные даты и праздники: on the 3rd of May / on Christmas Day"},
    {"sentence": "The book is {?} the table.",
     "answer": "on",  "translation": "Книга на столе.",
     "rule": "on — на горизонтальной поверхности (стол, пол, земля)"},
    {"sentence": "She lives {?} Baker Street.",
     "answer": "on",  "translation": "Она живёт на Бейкер-стрит.",
     "rule": "on — названия улиц: on Oxford Street / on Fifth Avenue"},
    {"sentence": "There is a picture {?} the wall.",
     "answer": "on",  "translation": "На стене висит картина.",
     "rule": "on — на вертикальной поверхности (стена, дверь, доска)"},
    {"sentence": "I saw it {?} TV.",
     "answer": "on",  "translation": "Я видел это по телевизору.",
     "rule": "on — средства медиа: on TV / on the radio / on the internet"},
    {"sentence": "We went there {?} foot.",
     "answer": "on",  "translation": "Мы пошли туда пешком.",
     "rule": "on foot — пешком; ср. by car / by bus / by train"},
    {"sentence": "She is {?} the phone right now.",
     "answer": "on",  "translation": "Она сейчас разговаривает по телефону.",
     "rule": "on the phone — разговор по телефону; on Zoom / on Skype"},
    {"sentence": "I read it {?} Facebook.",
     "answer": "on",  "translation": "Я прочитал это в Facebook.",
     "rule": "on — социальные сети: on Facebook / on Instagram / on Twitter"},
    {"sentence": "She is {?} holiday this week.",
     "answer": "on",  "translation": "На этой неделе она в отпуске.",
     "rule": "on holiday (BrE) = on vacation (AmE) — в отпуске или на каникулах"},
    {"sentence": "The flight arrived {?} time.",
     "answer": "on",  "translation": "Рейс прибыл вовремя.",
     "rule": "on time — точно по расписанию; ср. in time = успеть до дедлайна"},
    {"sentence": "They live {?} the third floor.",
     "answer": "on",  "translation": "Они живут на третьем этаже.",
     "rule": "on the floor — этажи здания: on the first / second / third floor"},
    {"sentence": "She congratulated him {?} his promotion.",
     "answer": "on",  "translation": "Она поздравила его с повышением.",
     "rule": "congratulate someone on — поздравить с достижением"},
    {"sentence": "The conference is {?} the 5th of March.",
     "answer": "on",  "translation": "Конференция — 5 марта.",
     "rule": "on — конкретная дата: on the 5th of March / on Saturday morning"},

    # ─── AT ──────────────────────────────────────────────────────────────────
    # Принцип: точное время; конкретная точка в пространстве; события

    {"sentence": "The train leaves {?} 9 o'clock.",
     "answer": "at",  "translation": "Поезд отправляется в 9 часов.",
     "rule": "at — точное время: at 7am / at noon / at midnight / at half past three"},
    {"sentence": "She is studying {?} university.",
     "answer": "at",  "translation": "Она учится в университете.",
     "rule": "at — учебные заведения (как деятельность): at school / at college / at university"},
    {"sentence": "I'll meet you {?} the airport.",
     "answer": "at",  "translation": "Встречу тебя в аэропорту.",
     "rule": "at — конкретная точка встречи: at the station / at the bus stop / at reception"},
    {"sentence": "She is good {?} maths.",
     "answer": "at",  "translation": "Она хорошо знает математику.",
     "rule": "good / bad / brilliant / terrible at — уровень умения или навыка"},
    {"sentence": "He arrived {?} the station.",
     "answer": "at",  "translation": "Он прибыл на станцию.",
     "rule": "arrive at — прибыть в конкретное место (здание, станция); arrive in — город или страна"},
    {"sentence": "They met {?} a party.",
     "answer": "at",  "translation": "Они познакомились на вечеринке.",
     "rule": "at — мероприятия и события: at a party / at a concert / at a conference"},
    {"sentence": "Look {?} that beautiful sunset!",
     "answer": "at",  "translation": "Посмотри на этот красивый закат!",
     "rule": "look at — смотреть на что-л.; ср. look for (искать), look after (присматривать)"},
    {"sentence": "She is working hard {?} the moment.",
     "answer": "at",  "translation": "Она сейчас усердно работает.",
     "rule": "at the moment — прямо сейчас (используется с Present Continuous)"},
    {"sentence": "He is {?} home all day.",
     "answer": "at",  "translation": "Он дома весь день.",
     "rule": "at home / at work / at school — функциональное место (что делает, а не где здание)"},
    {"sentence": "She is {?} work right now.",
     "answer": "at",  "translation": "Она сейчас на работе.",
     "rule": "at work — на рабочем месте, занят работой; ср. in the office = в офисе физически"},
    {"sentence": "We arrived {?} midnight.",
     "answer": "at",  "translation": "Мы приехали в полночь.",
     "rule": "at night / at midnight / at noon / at dawn — граничные точки суток"},
    {"sentence": "He knocked {?} the door.",
     "answer": "at",  "translation": "Он постучал в дверь.",
     "rule": "knock at / on the door — обращение к конкретной точке"},
    {"sentence": "She smiled {?} me from across the room.",
     "answer": "at",  "translation": "Она улыбнулась мне с другого конца комнаты.",
     "rule": "smile / wave / shout at — направленное действие в сторону кого-л."},
    {"sentence": "Let's meet {?} the entrance.",
     "answer": "at",  "translation": "Давай встретимся у входа.",
     "rule": "at + конкретная точка: at the entrance / at the corner / at the crossroads"},
    {"sentence": "The children are {?} school today.",
     "answer": "at",  "translation": "Сегодня дети в школе.",
     "rule": "at school (учатся) / in the school (физически внутри здания) — разный акцент"},
]
