VERB_PATTERNS = [

    # ─── + -ing ───────────────────────────────────────────────────────────────

    {"verb": "enjoy",      "pattern": "ing", "translation": "наслаждаться, получать удовольствие",
     "example": "I enjoy swimming in the sea.",
     "rule": "enjoy / love / hate / like + -ing — отношение к действию или устойчивая привычка"},
    {"verb": "dislike",    "pattern": "ing", "translation": "не любить, относиться негативно",
     "example": "She dislikes waiting for people.",
     "rule": "dislike + -ing — негативное отношение к действию (не употребляется с to)"},
    {"verb": "mind",       "pattern": "ing", "translation": "возражать (Do you mind...?)",
     "example": "Do you mind opening the window?",
     "rule": "mind + -ing: «вы не против...?» — вежливый вопрос о согласии"},
    {"verb": "fancy",      "pattern": "ing", "translation": "хотеть (неформально, BrE)",
     "example": "Do you fancy going out tonight?",
     "rule": "fancy + -ing (разг. брит.): «хочешь...?» — неформальное предложение"},
    {"verb": "miss",       "pattern": "ing", "translation": "скучать по чему-л., не хватает",
     "example": "I miss living near the sea.",
     "rule": "miss + -ing — тоска по прошлому или недоступному действию"},

    {"verb": "finish",     "pattern": "ing", "translation": "заканчивать делать что-л.",
     "example": "She finished reading the book.",
     "rule": "finish / quit / give up + -ing — завершение уже начатого действия"},
    {"verb": "avoid",      "pattern": "ing", "translation": "избегать, уклоняться",
     "example": "He avoids eating fast food.",
     "rule": "avoid + -ing — намеренное уклонение от действия"},
    {"verb": "delay",      "pattern": "ing", "translation": "откладывать, затягивать",
     "example": "Don't delay seeing a doctor if you feel unwell.",
     "rule": "delay / postpone / put off + -ing — перенос действия на потом"},
    {"verb": "postpone",   "pattern": "ing", "translation": "переносить, откладывать",
     "example": "They postponed making a final decision.",
     "rule": "postpone + -ing — официальный перенос чего-л. на более поздний срок"},
    {"verb": "resist",     "pattern": "ing", "translation": "удерживаться, не поддаваться",
     "example": "She couldn't resist laughing at his joke.",
     "rule": "resist + -ing — бороться с желанием что-то сделать"},
    {"verb": "deny",       "pattern": "ing", "translation": "отрицать, что делал что-л.",
     "example": "He denied taking the money.",
     "rule": "deny + -ing — отрицание прошлого действия; deny to не существует"},
    {"verb": "admit",      "pattern": "ing", "translation": "признавать, что делал что-л.",
     "example": "She admitted making a mistake.",
     "rule": "admit + -ing — признание прошлого действия (ср. deny + -ing)"},

    {"verb": "keep",       "pattern": "ing", "translation": "продолжать, не переставать",
     "example": "She keeps asking the same question.",
     "rule": "keep (on) + -ing — повторяющееся или непрерывное действие"},
    {"verb": "practise",   "pattern": "ing", "translation": "тренироваться, оттачивать навык",
     "example": "I practise speaking English every day.",
     "rule": "practise + -ing — целенаправленная отработка навыка"},
    {"verb": "risk",       "pattern": "ing", "translation": "рисковать, делая что-л.",
     "example": "Don't risk driving in such thick fog.",
     "rule": "risk + -ing — совершить действие, невзирая на опасность"},
    {"verb": "involve",    "pattern": "ing", "translation": "предполагать, включать в себя",
     "example": "The job involves travelling abroad regularly.",
     "rule": "involve + -ing: «эта работа предполагает...» — действие как часть чего-л."},

    {"verb": "consider",   "pattern": "ing", "translation": "обдумывать, рассматривать вариант",
     "example": "I am considering moving to another city.",
     "rule": "consider + -ing — мысленное обдумывание возможного действия"},
    {"verb": "imagine",    "pattern": "ing", "translation": "представлять себе",
     "example": "Imagine living on a tropical island!",
     "rule": "imagine + -ing — мысленная картина действия"},
    {"verb": "recall",     "pattern": "ing", "translation": "вспоминать конкретный момент",
     "example": "I recall meeting her once at a conference.",
     "rule": "recall + -ing — воспоминание о прошлом событии"},

    {"verb": "suggest",    "pattern": "ing", "translation": "предлагать (идею, план)",
     "example": "She suggested going by bus.",
     "rule": "suggest + -ing (не suggest to!): «предлагаю сделать»"},
    {"verb": "recommend",  "pattern": "ing", "translation": "рекомендовать",
     "example": "The doctor recommended taking a short break.",
     "rule": "recommend + -ing (не recommend to!): совет или рекомендация"},

    # ─── + to ─────────────────────────────────────────────────────────────────

    {"verb": "want",       "pattern": "to",  "translation": "хотеть сделать что-л.",
     "example": "I want to learn English fluently.",
     "rule": "want / wish / would like + to — желание или стремление"},
    {"verb": "hope",       "pattern": "to",  "translation": "надеяться сделать что-л.",
     "example": "I hope to see you soon.",
     "rule": "hope + to — оптимистичное ожидание будущего события"},
    {"verb": "plan",       "pattern": "to",  "translation": "планировать",
     "example": "We plan to travel to Japan this summer.",
     "rule": "plan / intend / aim + to — конкретное намерение или план"},
    {"verb": "intend",     "pattern": "to",  "translation": "намереваться",
     "example": "I intend to finish this project by Friday.",
     "rule": "intend + to — намеренное, заранее обдуманное решение"},
    {"verb": "decide",     "pattern": "to",  "translation": "решать (принять решение)",
     "example": "She decided to stay at home.",
     "rule": "decide + to — момент принятия решения"},
    {"verb": "choose",     "pattern": "to",  "translation": "выбирать, предпочитать",
     "example": "He chose to ignore the warning.",
     "rule": "choose + to — сознательный выбор действия"},

    {"verb": "agree",      "pattern": "to",  "translation": "соглашаться сделать что-л.",
     "example": "They agreed to help us with the project.",
     "rule": "agree + to — принятие предложения или просьбы"},
    {"verb": "refuse",     "pattern": "to",  "translation": "отказываться делать что-л.",
     "example": "She refused to answer any questions.",
     "rule": "refuse + to — категоричный отказ"},
    {"verb": "offer",      "pattern": "to",  "translation": "предлагать помощь или услугу",
     "example": "He offered to drive me to the airport.",
     "rule": "offer + to — инициативное предложение помощи"},
    {"verb": "promise",    "pattern": "to",  "translation": "обещать сделать что-л.",
     "example": "He promised to call me back.",
     "rule": "promise + to — обещание выполнить действие в будущем"},
    {"verb": "demand",     "pattern": "to",  "translation": "требовать, настаивать",
     "example": "She demanded to speak to the manager.",
     "rule": "demand + to — настойчивое, категоричное требование"},

    {"verb": "manage",     "pattern": "to",  "translation": "суметь, справиться (с трудом)",
     "example": "He managed to finish the report on time.",
     "rule": "manage + to — успешно выполнить трудное действие (≠ fail + to)"},
    {"verb": "fail",       "pattern": "to",  "translation": "не суметь, не справиться",
     "example": "She failed to pass the exam twice.",
     "rule": "fail + to — не выполнить то, что планировалось (≠ manage + to)"},
    {"verb": "afford",     "pattern": "to",  "translation": "позволить себе (финансово или морально)",
     "example": "I can't afford to buy a new car right now.",
     "rule": "afford + to — наличие или отсутствие ресурсов (обычно can't afford)"},

    {"verb": "seem",       "pattern": "to",  "translation": "казаться, производить впечатление",
     "example": "He seems to know all the answers.",
     "rule": "seem / appear + to — описание внешнего впечатления или вида"},
    {"verb": "appear",     "pattern": "to",  "translation": "казаться, выглядеть как будто",
     "example": "She appears to be very confident in herself.",
     "rule": "appear + to — формальный аналог seem; описание впечатления"},
    {"verb": "tend",       "pattern": "to",  "translation": "иметь склонность, обычно делать",
     "example": "She tends to worry about things she can't control.",
     "rule": "tend + to — устойчивая привычка или характерная черта"},
    {"verb": "pretend",    "pattern": "to",  "translation": "притворяться, делать вид",
     "example": "He pretended not to hear what she said.",
     "rule": "pretend + to — симуляция действия"},
    {"verb": "expect",     "pattern": "to",  "translation": "ожидать, предполагать",
     "example": "I expect to hear from him by tomorrow.",
     "rule": "expect + to — ожидание будущего события"},
    {"verb": "prepare",    "pattern": "to",  "translation": "готовиться сделать что-л.",
     "example": "She prepared to give a speech in front of the audience.",
     "rule": "prepare + to — подготовка к конкретному предстоящему действию"},
    {"verb": "learn",      "pattern": "to",  "translation": "научиться делать что-л.",
     "example": "He learned to swim at the age of five.",
     "rule": "learn + to — освоение нового навыка через обучение или практику"},
    {"verb": "arrange",    "pattern": "to",  "translation": "договориться, организовать",
     "example": "I arranged to meet her at the café at noon.",
     "rule": "arrange + to — заранее запланировать встречу или событие"},

    # ─── Двойные глаголы: смысл меняется в зависимости от формы ──────────────

    {"verb": "stop  (прекратить)",        "pattern": "ing", "translation": "прекратить делать что-л.",
     "example": "He stopped smoking three years ago. (= he no longer smokes)",
     "rule": "stop + -ing = прекратить действие. Ср.: stop to do = остановиться чтобы начать другое"},
    {"verb": "stop  (остановиться чтобы)", "pattern": "to",  "translation": "остановиться, чтобы сделать",
     "example": "She stopped to buy a coffee on the way to work.",
     "rule": "stop + to do = прервать одно действие, чтобы начать другое"},

    {"verb": "remember  (о прошлом)",     "pattern": "ing", "translation": "помнить, что делал",
     "example": "I remember meeting her at that party. (= I have a memory of it)",
     "rule": "remember + -ing = воспоминание о прошлом событии"},
    {"verb": "remember  (о будущем)",     "pattern": "to",  "translation": "не забыть сделать",
     "example": "Remember to lock the door before you leave!",
     "rule": "remember + to = не забыть выполнить задачу в будущем"},

    {"verb": "try  (эксперимент)",        "pattern": "ing", "translation": "попробовать (посмотреть, что выйдет)",
     "example": "Try adding more garlic — it might taste better.",
     "rule": "try + -ing = попробовать другой подход как эксперимент"},
    {"verb": "try  (попытка)",            "pattern": "to",  "translation": "пытаться, стараться",
     "example": "She tried to open the jar but couldn't.",
     "rule": "try + to = прилагать усилия для достижения цели"},

    {"verb": "forget  (о прошлом)",       "pattern": "ing", "translation": "не помнить, что делал",
     "example": "I'll never forget visiting Paris for the first time.",
     "rule": "forget + -ing = не помнить прошлого события"},
    {"verb": "forget  (о будущем)",       "pattern": "to",  "translation": "забыть выполнить задачу",
     "example": "Don't forget to send me that file!",
     "rule": "forget + to = не выполнить задачу из-за забывчивости"},
]
