VERBS = [
    {"v1": "be",          "v2": "was/were",   "v3": "been",
     "translation": "быть, являться",
     "example": "She was very tired after the long trip.",
     "note": "I/he/she/it → was; you/we/they → were"},
    {"v1": "beat",        "v2": "beat",        "v3": "beaten",
     "translation": "побеждать, бить",
     "example": "Our team beat the champions in the final."},
    {"v1": "become",      "v2": "became",      "v3": "become",
     "translation": "становиться",
     "example": "He became a famous doctor."},
    {"v1": "begin",       "v2": "began",       "v3": "begun",
     "translation": "начинать",
     "example": "The concert began at eight o'clock."},
    {"v1": "bend",        "v2": "bent",        "v3": "bent",
     "translation": "гнуть, сгибать",
     "example": "She bent down to pick up the keys."},
    {"v1": "bite",        "v2": "bit",         "v3": "bitten",
     "translation": "кусать",
     "example": "The dog bit the postman on the ankle."},
    {"v1": "blow",        "v2": "blew",        "v3": "blown",
     "translation": "дуть",
     "example": "The wind blew all the papers off the desk."},
    {"v1": "break",       "v2": "broke",       "v3": "broken",
     "translation": "ломать",
     "example": "He broke his arm playing football."},
    {"v1": "bring",       "v2": "brought",     "v3": "brought",
     "translation": "приносить",
     "example": "She brought flowers to the party."},
    {"v1": "build",       "v2": "built",       "v3": "built",
     "translation": "строить",
     "example": "They built a new house last year."},
    {"v1": "burn",        "v2": "burnt",       "v3": "burnt",
     "translation": "гореть, жечь",
     "example": "She burnt the toast again.",
     "note": "burnt (BrE) и burned (AmE) — оба варианта V2/V3 правильны"},
    {"v1": "buy",         "v2": "bought",      "v3": "bought",
     "translation": "покупать",
     "example": "I bought a new laptop yesterday."},
    {"v1": "catch",       "v2": "caught",      "v3": "caught",
     "translation": "ловить, поймать",
     "example": "The dog caught the ball in the air."},
    {"v1": "choose",      "v2": "chose",       "v3": "chosen",
     "translation": "выбирать",
     "example": "She chose the blue dress for the event."},
    {"v1": "come",        "v2": "came",        "v3": "come",
     "translation": "приходить, приезжать",
     "example": "He came home very late last night."},
    {"v1": "cost",        "v2": "cost",        "v3": "cost",
     "translation": "стоить",
     "example": "The ticket cost fifty dollars."},
    {"v1": "cut",         "v2": "cut",         "v3": "cut",
     "translation": "резать",
     "example": "She cut the cake into eight pieces."},
    {"v1": "deal",        "v2": "dealt",       "v3": "dealt",
     "translation": "иметь дело, справляться",
     "example": "She dealt with the problem quickly and professionally."},
    {"v1": "dig",         "v2": "dug",         "v3": "dug",
     "translation": "копать",
     "example": "The dog dug a hole in the garden."},
    {"v1": "do",          "v2": "did",         "v3": "done",
     "translation": "делать",
     "example": "I did my homework before dinner."},
    {"v1": "draw",        "v2": "drew",        "v3": "drawn",
     "translation": "рисовать",
     "example": "She drew a beautiful portrait of her sister."},
    {"v1": "drink",       "v2": "drank",       "v3": "drunk",
     "translation": "пить",
     "example": "He drank two cups of coffee in the morning."},
    {"v1": "drive",       "v2": "drove",       "v3": "driven",
     "translation": "водить машину",
     "example": "She drove to work every day last winter."},
    {"v1": "eat",         "v2": "ate",         "v3": "eaten",
     "translation": "есть, кушать",
     "example": "We ate dinner at a nice restaurant."},
    {"v1": "fall",        "v2": "fell",        "v3": "fallen",
     "translation": "падать",
     "example": "The leaves fell from the trees in autumn."},
    {"v1": "feed",        "v2": "fed",         "v3": "fed",
     "translation": "кормить",
     "example": "She fed the cat and then made breakfast."},
    {"v1": "feel",        "v2": "felt",        "v3": "felt",
     "translation": "чувствовать",
     "example": "She felt tired after the long run."},
    {"v1": "fight",       "v2": "fought",      "v3": "fought",
     "translation": "бороться, драться",
     "example": "They fought for the championship title."},
    {"v1": "find",        "v2": "found",       "v3": "found",
     "translation": "находить",
     "example": "I found my keys under the sofa."},
    {"v1": "fly",         "v2": "flew",        "v3": "flown",
     "translation": "летать",
     "example": "The bird flew over our house."},
    {"v1": "forget",      "v2": "forgot",      "v3": "forgotten",
     "translation": "забывать",
     "example": "I forgot my umbrella at home again."},
    {"v1": "freeze",      "v2": "froze",       "v3": "frozen",
     "translation": "замерзать, замораживать",
     "example": "The lake froze completely during the cold winter."},
    {"v1": "get",         "v2": "got",         "v3": "got/gotten",
     "translation": "получать, становиться",
     "example": "She got a promotion at work last month.",
     "note": "got (BrE) и gotten (AmE) — оба варианта V3 правильны"},
    {"v1": "give",        "v2": "gave",        "v3": "given",
     "translation": "давать",
     "example": "He gave her a beautiful birthday present."},
    {"v1": "go",          "v2": "went",        "v3": "gone",
     "translation": "идти, ехать",
     "example": "They went to Paris last summer."},
    {"v1": "grow",        "v2": "grew",        "v3": "grown",
     "translation": "расти",
     "example": "The plant grew very fast in the sun."},
    {"v1": "hang",        "v2": "hung",        "v3": "hung",
     "translation": "висеть, вешать (предметы)",
     "example": "She hung her coat on the hook by the door.",
     "note": "hung — для предметов; hanged — только в юридическом контексте (казнь)"},
    {"v1": "have",        "v2": "had",         "v3": "had",
     "translation": "иметь",
     "example": "She had a brilliant idea this morning."},
    {"v1": "hear",        "v2": "heard",       "v3": "heard",
     "translation": "слышать",
     "example": "I heard a strange noise outside the window."},
    {"v1": "hide",        "v2": "hid",         "v3": "hidden",
     "translation": "прятать(ся)",
     "example": "The cat hid under the bed during the storm."},
    {"v1": "hit",         "v2": "hit",         "v3": "hit",
     "translation": "ударять",
     "example": "The ball hit the window and cracked it."},
    {"v1": "hold",        "v2": "held",        "v3": "held",
     "translation": "держать",
     "example": "She held the baby carefully in her arms."},
    {"v1": "hurt",        "v2": "hurt",        "v3": "hurt",
     "translation": "причинять боль, болеть",
     "example": "He hurt his knee during training."},
    {"v1": "keep",        "v2": "kept",        "v3": "kept",
     "translation": "держать, хранить",
     "example": "He kept all her letters in a box."},
    {"v1": "know",        "v2": "knew",        "v3": "known",
     "translation": "знать",
     "example": "She knew the answer immediately."},
    {"v1": "lay",         "v2": "laid",        "v3": "laid",
     "translation": "класть, укладывать (что-л.)",
     "example": "She laid the baby carefully in the cot.",
     "note": "lay = класть что-то (переходный). Не путать с lie/lay/lain = лежать"},
    {"v1": "lead",        "v2": "led",         "v3": "led",
     "translation": "вести, руководить",
     "example": "She led the team to victory."},
    {"v1": "leave",       "v2": "left",        "v3": "left",
     "translation": "уходить, оставлять",
     "example": "He left his job last month."},
    {"v1": "lend",        "v2": "lent",        "v3": "lent",
     "translation": "одалживать (давать взаймы)",
     "example": "She lent me her umbrella for the day."},
    {"v1": "let",         "v2": "let",         "v3": "let",
     "translation": "разрешать, позволять",
     "example": "His parents let him stay out until midnight."},
    {"v1": "light",       "v2": "lit",         "v3": "lit",
     "translation": "зажигать, освещать",
     "example": "She lit a candle and placed it on the table."},
    {"v1": "lose",        "v2": "lost",        "v3": "lost",
     "translation": "терять, проигрывать",
     "example": "He lost his wallet at the train station."},
    {"v1": "make",        "v2": "made",        "v3": "made",
     "translation": "делать, создавать",
     "example": "She made a delicious chocolate cake."},
    {"v1": "mean",        "v2": "meant",       "v3": "meant",
     "translation": "значить, иметь в виду",
     "example": "I didn't mean to upset you."},
    {"v1": "meet",        "v2": "met",         "v3": "met",
     "translation": "встречать",
     "example": "We met at the coffee shop by chance."},
    {"v1": "pay",         "v2": "paid",        "v3": "paid",
     "translation": "платить",
     "example": "He paid for dinner and left a tip."},
    {"v1": "put",         "v2": "put",         "v3": "put",
     "translation": "класть, ставить",
     "example": "She put the book back on the shelf."},
    {"v1": "quit",        "v2": "quit",        "v3": "quit",
     "translation": "бросать, увольняться",
     "example": "He quit his job to start his own business.",
     "note": "quit/quit/quit (AmE); quitted — устаревшая BrE форма"},
    {"v1": "read",        "v2": "read",        "v3": "read",
     "translation": "читать",
     "example": "He read the newspaper every morning.",
     "note": "Пишется одинаково: read, но V2/V3 произносится /red/ (как слово 'red')"},
    {"v1": "ride",        "v2": "rode",        "v3": "ridden",
     "translation": "ехать верхом, кататься",
     "example": "She rode her bike to school every day."},
    {"v1": "rise",        "v2": "rose",        "v3": "risen",
     "translation": "подниматься (самостоятельно)",
     "example": "The sun rose at six o'clock this morning.",
     "note": "rise = подниматься самому (непереходный). Ср. raise/raised/raised = поднимать что-то"},
    {"v1": "run",         "v2": "ran",         "v3": "run",
     "translation": "бегать",
     "example": "He ran five kilometres before breakfast."},
    {"v1": "say",         "v2": "said",        "v3": "said",
     "translation": "говорить, сказать",
     "example": "She said goodbye and walked out."},
    {"v1": "see",         "v2": "saw",         "v3": "seen",
     "translation": "видеть",
     "example": "I saw a great film last night."},
    {"v1": "sell",        "v2": "sold",        "v3": "sold",
     "translation": "продавать",
     "example": "They sold their old car last week."},
    {"v1": "send",        "v2": "sent",        "v3": "sent",
     "translation": "отправлять",
     "example": "She sent me a message this morning."},
    {"v1": "shake",       "v2": "shook",       "v3": "shaken",
     "translation": "трясти, встряхивать",
     "example": "He shook the bottle before opening it."},
    {"v1": "shoot",       "v2": "shot",        "v3": "shot",
     "translation": "стрелять, снимать (фото/видео)",
     "example": "The photographer shot over two hundred photos."},
    {"v1": "show",        "v2": "showed",      "v3": "shown",
     "translation": "показывать",
     "example": "He showed us his new apartment."},
    {"v1": "shut",        "v2": "shut",        "v3": "shut",
     "translation": "закрывать",
     "example": "She shut the window because of the noise."},
    {"v1": "sing",        "v2": "sang",        "v3": "sung",
     "translation": "петь",
     "example": "She sang a beautiful song at the concert."},
    {"v1": "sink",        "v2": "sank",        "v3": "sunk",
     "translation": "тонуть, погружаться",
     "example": "The boat sank in less than ten minutes."},
    {"v1": "sit",         "v2": "sat",         "v3": "sat",
     "translation": "сидеть",
     "example": "We sat by the fireplace all evening."},
    {"v1": "sleep",       "v2": "slept",       "v3": "slept",
     "translation": "спать",
     "example": "The baby slept through the whole night."},
    {"v1": "slide",       "v2": "slid",        "v3": "slid",
     "translation": "скользить, съезжать",
     "example": "The children slid down the snowy hill."},
    {"v1": "speak",       "v2": "spoke",       "v3": "spoken",
     "translation": "говорить, разговаривать",
     "example": "She spoke three languages fluently."},
    {"v1": "spend",       "v2": "spent",       "v3": "spent",
     "translation": "тратить (время / деньги)",
     "example": "We spent a whole week in Rome."},
    {"v1": "spread",      "v2": "spread",      "v3": "spread",
     "translation": "распространять, намазывать",
     "example": "She spread butter on her toast."},
    {"v1": "stand",       "v2": "stood",       "v3": "stood",
     "translation": "стоять",
     "example": "He stood at the door waiting for an hour."},
    {"v1": "steal",       "v2": "stole",       "v3": "stolen",
     "translation": "красть",
     "example": "Someone stole his bicycle from the yard."},
    {"v1": "stick",       "v2": "stuck",       "v3": "stuck",
     "translation": "прилипать, застревать",
     "example": "The key got stuck in the lock."},
    {"v1": "strike",      "v2": "struck",      "v3": "struck",
     "translation": "ударять, поражать",
     "example": "Lightning struck the tree during the storm."},
    {"v1": "sweep",       "v2": "swept",       "v3": "swept",
     "translation": "подметать, сметать",
     "example": "She swept the kitchen floor every morning."},
    {"v1": "swim",        "v2": "swam",        "v3": "swum",
     "translation": "плавать",
     "example": "She swam across the lake in twenty minutes."},
    {"v1": "take",        "v2": "took",        "v3": "taken",
     "translation": "брать, взять",
     "example": "He took a taxi to the airport."},
    {"v1": "teach",       "v2": "taught",      "v3": "taught",
     "translation": "учить, преподавать",
     "example": "She taught English for twenty years."},
    {"v1": "tear",        "v2": "tore",        "v3": "torn",
     "translation": "рвать, разрывать",
     "example": "He accidentally tore the page out of the book."},
    {"v1": "tell",        "v2": "told",        "v3": "told",
     "translation": "рассказывать, говорить",
     "example": "He told us a very interesting story."},
    {"v1": "think",       "v2": "thought",     "v3": "thought",
     "translation": "думать",
     "example": "I thought about it all day long."},
    {"v1": "throw",       "v2": "threw",       "v3": "thrown",
     "translation": "бросать",
     "example": "He threw the ball high into the air."},
    {"v1": "understand",  "v2": "understood",  "v3": "understood",
     "translation": "понимать",
     "example": "She understood the problem immediately."},
    {"v1": "upset",       "v2": "upset",       "v3": "upset",
     "translation": "расстраивать, огорчать",
     "example": "The bad news upset everyone in the team."},
    {"v1": "wake",        "v2": "woke",        "v3": "woken",
     "translation": "просыпаться, будить",
     "example": "I woke up very early this morning."},
    {"v1": "wear",        "v2": "wore",        "v3": "worn",
     "translation": "носить (одежду)",
     "example": "She wore a red dress to the party."},
    {"v1": "win",         "v2": "won",         "v3": "won",
     "translation": "побеждать, выигрывать",
     "example": "Our team won the championship last year."},
    {"v1": "wind",        "v2": "wound",       "v3": "wound",
     "translation": "наматывать, заводить (часы)",
     "example": "He wound the clock before going to bed.",
     "note": "wound (V2/V3) произносится /waʊnd/; не путать с wound /wuːnd/ = рана"},
    {"v1": "write",       "v2": "wrote",       "v3": "written",
     "translation": "писать",
     "example": "He wrote a long letter to his old friend."},
    {"v1": "bear",        "v2": "bore",        "v3": "borne",
     "translation": "терпеть, выносить",
     "example": "She bore the pain bravely."},
    {"v1": "bet",         "v2": "bet",         "v3": "bet",
     "translation": "держать пари, ставить",
     "example": "I bet he forgets our meeting again."},
    {"v1": "burst",       "v2": "burst",       "v3": "burst",
     "translation": "лопаться, взрываться",
     "example": "The balloon burst with a loud bang."},
    {"v1": "dream",       "v2": "dreamt/dreamed", "v3": "dreamt/dreamed",
     "translation": "мечтать, видеть сны",
     "example": "She dreamt about flying over the ocean.",
     "note": "dreamt (BrE) и dreamed (AmE) — оба варианта правильны"},
    {"v1": "forbid",      "v2": "forbade",     "v3": "forbidden",
     "translation": "запрещать",
     "example": "Her parents forbade her to stay out late."},
    {"v1": "forgive",     "v2": "forgave",     "v3": "forgiven",
     "translation": "прощать",
     "example": "She forgave him for being late again."},
    {"v1": "learn",       "v2": "learnt/learned", "v3": "learnt/learned",
     "translation": "учить, узнавать",
     "example": "He learnt to swim when he was five.",
     "note": "learnt (BrE) и learned (AmE) — оба варианта правильны"},
    {"v1": "lie",         "v2": "lay",         "v3": "lain",
     "translation": "лежать",
     "example": "He lay on the sofa all afternoon.",
     "note": "не путай с lay/laid/laid = класть; lie (лгать) — правильный: lied/lied"},
    {"v1": "prove",       "v2": "proved",      "v3": "proved/proven",
     "translation": "доказывать",
     "example": "She has proven her point with real numbers.",
     "note": "proven чаще в AmE; proved тоже верно"},
    {"v1": "ring",        "v2": "rang",        "v3": "rung",
     "translation": "звонить, звенеть",
     "example": "The phone rang in the middle of the night."},
    {"v1": "seek",        "v2": "sought",      "v3": "sought",
     "translation": "искать, добиваться",
     "example": "They sought shelter from the storm."},
    {"v1": "set",         "v2": "set",         "v3": "set",
     "translation": "ставить, устанавливать",
     "example": "She set the table for dinner."},
    {"v1": "shine",       "v2": "shone",       "v3": "shone",
     "translation": "светить, сиять",
     "example": "The sun shone brightly all day."},
    {"v1": "smell",       "v2": "smelt/smelled", "v3": "smelt/smelled",
     "translation": "пахнуть, нюхать",
     "example": "The kitchen smelt of fresh bread.",
     "note": "smelt (BrE) и smelled (AmE) — оба варианта правильны"},
    {"v1": "spell",       "v2": "spelt/spelled", "v3": "spelt/spelled",
     "translation": "писать/произносить по буквам",
     "example": "She spelt her surname twice on the phone.",
     "note": "spelt (BrE) и spelled (AmE) — оба варианта правильны"},
    {"v1": "spill",       "v2": "spilt/spilled", "v3": "spilt/spilled",
     "translation": "проливать",
     "example": "He spilt coffee all over his shirt.",
     "note": "spilt (BrE) и spilled (AmE) — оба варианта правильны"},
    {"v1": "split",       "v2": "split",       "v3": "split",
     "translation": "делить(ся), раскалывать",
     "example": "They split the bill after dinner."},
    {"v1": "spoil",       "v2": "spoilt/spoiled", "v3": "spoilt/spoiled",
     "translation": "портить, баловать",
     "example": "The rain spoilt our picnic completely.",
     "note": "spoilt (BrE) и spoiled (AmE) — оба варианта правильны"},
    {"v1": "swear",       "v2": "swore",       "v3": "sworn",
     "translation": "клясться; ругаться",
     "example": "He swore to tell the whole truth."},
    {"v1": "swing",       "v2": "swung",       "v3": "swung",
     "translation": "качать(ся), размахивать",
     "example": "The monkey swung from branch to branch."},
]
